adding custom stub
browserstack/a11y-engine-axe-core pull request #74
Opened 2024-07-30 08:38 UTC by SuyashSonawane

DOMForge Core requires changes in axe-core. By default when axe-core is injected in webpage an anonymous function is executed and axe get initialised on global window object, this is not the preferred in DOMForge.

Closes https://browserstack.atlassian.net/browse/AXE-342

2024-07-30 08:43 UTC, sajalg-bstack approved these changes

2024-07-30 08:45 UTC, Abhi3685 approved these changes

2024-07-30 08:50 UTC, ansh21 requested changes

2024-07-30 08:50 UTC, ansh21 commented on Gruntfile.js
> -              'lib/intro.stub',
no UTs?

2024-07-31 05:41 UTC, ansh21 approved these changes

2024-08-01 11:11 UTC, merged