Release 3.0.0
browserstack/a11y-engine-axe-core pull request #98
Opened 2024-09-18 12:41 UTC by mattscepter

<< Describe the changes >>

Closes:

2024-09-18 13:20 UTC, sajalg-bstack commented on lib/commons/dom/get-visible-child-text-rects.js
> +
[nit] Unwanted empty space

2024-09-18 13:20 UTC, sajalg-bstack commented on lib/commons/dom/get-overflow-hidden-ancestors.js
> +    if (cache.get('200%ZoomRule')) {
cache.set is present in another PR?

2024-09-18 17:12 UTC, Abhi3685 requested changes

2024-09-18 17:12 UTC, Abhi3685 commented on lib/commons/dom/create-grid.js
> +    }
where is this property getting set?

2024-09-18 17:12 UTC, Abhi3685 commented on lib/commons/dom/get-element-stack.js
> +function getElementStack(node, isCoordsPassed = false, x, y) {
default arguments should be at the end - x & y should also be defaults?

2024-09-18 17:12 UTC, Abhi3685 commented on lib/commons/dom/get-rect-stack.js
> +  recursed = false,
default arguments should be at the end - there must not be any mandatory arguments after default arguments

2024-09-19 08:07 UTC, Abhi3685 submitted a review, later dismissed

2024-10-14 14:08 UTC, merged